apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cUmAF5OzW2xqQxfdB5TiB+BUJ77O9Gg+7CemkYpSud4nUsZNihiYkAC7oetTv7KheY29/ZsWFL2tNVnQS/AQjZo/YJG2u1upswcMXchvnapHfdU0gBm1f0lJPgg8fickv0yxA6CfNfQ0miN4HqRCP7DtMCHVqOyY/6e7fmmweVceC7Uq+EW7zzZYxr5Gz8lrPWrR4Q2/yjlx/tLLBMRkjXG0Uv3bPY9LN9q/rd/jSu/sdl8tibnJ1+5AiH8c29sA1mQtDH9Z3UzHkB0m+OyNIAM7OYUUzkTatTI1rd9MhNj3AF9gcNBGJfeL+Js=,iv:WVWqFJowp4hPIu4Pu1SM7vHEt5IUx21jbs9KPrpW/Ig=,tag:yQBctIV2F/vvvo1AbhCWxA==,type:str]
kind: Secret
metadata:
    name: abs-tunnel-creds
    namespace: audiobookshelf
sops:
    age:
        - recipient: age1cm4nkpv34qreyhlpwwdu7rt0d4y7ss0c0tgxseynpg7m2gsh5g4qn2dhja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVkF4ei84UzhtcnRmb2NK
            UzlyaFZ1RWpNcGZqWS9RMFJPZXRuaHFPUkJ3ClUrRmc0UVJub3JZTnpMMEpzOStw
            bGFTeDFHK29nY3ZTVVBPNWxFaWF6K00KLS0tIGliNllSQ0RpN2JRMTJvSlBoMlNv
            dkJXRVhYU3FicWJpaTNkTWh0RnlnSzQK6CatsPBf4lvTP2EmC6TC19m8ZBpB4Ibh
            swbYJ0v7cKXIOYB4nCbJRW3v0cMWKsV5zb50a4rYU0kkOZ312oas9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T14:06:36Z"
    mac: ENC[AES256_GCM,data:eFLGIOOZNmqq4NVAkNTTRqNAMBEGHDfrOxBIr8j+/Huw3iGgZYAgMldac7/7gLkHeb1Exm4Gm+pMKIvT/LLs+5kwlOzodHmilAmfcJb6HT1pmxRK8GcUsJ4d5nAc6iIV+/P38iODnu67SiW7je70mXQd5Sl5E8QX62cXtCsm4C0=,iv:4LylOtBARRkROQCs7vnMJ8PE6Mmyp3mvBXONHxyRkFo=,tag:VBtDHUXoBPNNy9dvRT6ozw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
